### ISSUE TITLE
Não roda no CMD do Windows

### ISSUE THREAD

**Issue by daniellucasdev** [ArtuTerra/Matrix#1]
Aplicação buga se executada pelo CMD do Windows: 
![image](https://user-images.githubusercontent.com/105459960/217322343-d500990b-1f3b-4d3b-8752-93b27fd348fc.png)

**Comment by ArtuTerra** [comment]
Fiz uma outra versão do programa que rode em windows agora, mas não roda em linux por usar um diretório do windows.
![image](https://user-images.githubusercontent.com/121909513/217340748-08e9a10e-7abe-4bbd-ba20-dfce824cf77c.png)
